#!/usr/bin/env bash
# Bash script that installs and configures the 'ufw' firewall.
# Install ufw if it is not already installed
apt-get update
apt-get install -y ufw

sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

ufw disable
ufw enable

ufw default deny incoming
ufw default allow outgoing

ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp

ufw reload

echo "Firewall configuration completed. Ports 22, 80, and 443 are allowed."
